# Generated by Django 2.1.1 on 2020-05-02 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('enrollments', '0002_auto_20200502_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='studentEnrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.StudentUser'),
        ),
    ]
