language: python
python:
    - "3.6"
cache: pip3
branches:
   only:
    - master
   env:
    - DJANGO=3.0
   before_install:
    - cd app/
   install:
    - "pip3 install -r requirements.txt"
    script: 
    - python3 app/manage.py test