# Generated by Django 2.1.1 on 2020-05-10 23:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='documentIdUser',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Numero incorrecto', regex='^\\+?1?\\d{1,10}$')], verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='passwordUser',
            field=models.CharField(default=[models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Numero incorrecto', regex='^\\+?1?\\d{1,10}$')], verbose_name='ID')], max_length=200),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phoneUser',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Numero incorrecto', regex='^\\+?1?\\d{1,10}$')]),
        ),
    ]
