# Generated by Django 2.1.1 on 2020-07-15 02:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.CharField(blank=True, default='https://res.cloudinary.com/sigeedu/image/upload/v1594776164/sigedu/1528904524_boy_1_wehjsw.svg', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='documentIdUser',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Numero incorrecto', regex='^\\+?1?\\d{7,10}$')], verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='passwordUser',
            field=models.CharField(default=[models.CharField(max_length=30, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Numero incorrecto', regex='^\\+?1?\\d{7,10}$')], verbose_name='ID')], max_length=200),
        ),
    ]
