# Generated by Django 2.1.1 on 2020-04-29 22:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200429_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phoneUser',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Numero incorrecto', regex='^\\+?1?\\d{7,10}$')]),
        ),
    ]
