# Generated by Django 2.1.1 on 2020-04-29 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200429_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='emailUser',
            field=models.EmailField(blank=True, max_length=70),
        ),
    ]
