# Generated by Django 2.1.1 on 2020-08-06 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_forum',
            name='feed_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infos', to='forum.Feed'),
        ),
        migrations.AlterField(
            model_name='replay_feed_forum',
            name='replay_feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replays', to='forum.Feed'),
        ),
    ]
