# Generated by Django 2.1.1 on 2020-08-12 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20200806_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='date_feed',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
