# Generated by Django 2.1.1 on 2020-05-13 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorials',
            fields=[
                ('codeTutorial', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameTutorial', models.CharField(max_length=255)),
                ('typeTutorial', models.CharField(max_length=500)),
                ('urlTutorial', models.CharField(max_length=500)),
                ('likeTutorial', models.PositiveIntegerField()),
            ],
        ),
    ]
