# Generated by Django 2.1 on 2020-04-16 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalInstitution',
            fields=[
                ('codeIE', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameIE', models.CharField(max_length=100, null=True, unique=True)),
                ('nitIE', models.CharField(max_length=100, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Headquarters',
            fields=[
                ('codeHeadquarters', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameHeadquarters', models.CharField(max_length=100)),
                ('daneHeadquarters', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('codeIE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.EducationalInstitution')),
            ],
        ),
    ]
