# Generated by Django 2.1.1 on 2020-05-25 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secctions', '0002_auto_20200524_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsesecction',
            name='secctionResponse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='secctions.Secction'),
        ),
    ]
