# Generated by Django 2.1.1 on 2020-06-16 01:35

from django.db import migrations, models
import django.db.models.deletion
import secctions.models


class Migration(migrations.Migration):

    dependencies = [
        ('secctions', '0004_auto_20200525_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='secctionResource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='secctions.Secction'),
        ),
        migrations.AlterField(
            model_name='responsesecction',
            name='response',
            field=models.FileField(blank=True, upload_to=secctions.models.get_upload_response_path),
        ),
    ]
