# Generated by Django 2.1.1 on 2020-06-16 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secctions', '0005_auto_20200616_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hyperlynks',
            name='secctionHyperlink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lynks', to='secctions.Secction'),
        ),
    ]
