# Generated by Django 2.1.1 on 2020-06-16 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secctions', '0006_auto_20200616_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsesecction',
            name='secctionResponse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='secctions.Secction'),
        ),
    ]
