# Generated by Django 2.1.1 on 2020-07-21 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secctions', '0007_auto_20200616_0438'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='score',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
