# Generated by Django 2.1.1 on 2020-07-21 15:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('secctions', '0011_secction_image_found'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secction',
            name='date_close',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
