# Generated by Django 2.1.1 on 2020-07-30 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secctions', '0013_auto_20200722_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='responseToComment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='secctions.Responses'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='response_secction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='secctions.Responses'),
        ),
    ]
