# Generated by Django 2.1.1 on 2020-05-01 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSpace',
            fields=[
                ('codeWorkSpace', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameWorkSpace', models.CharField(max_length=100)),
                ('descriptionWorkSpace', models.CharField(max_length=255)),
                ('academicCharge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.AcademicCharge')),
            ],
        ),
    ]
