# Generated by Django 2.1.1 on 2020-08-07 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('secctions', '0017_auto_20200730_0509'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField(max_length=5000, null=True)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='secctions.Responses')),
            ],
        ),
    ]
