# Generated by Django 2.1.1 on 2020-05-24 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_photouser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhotoUser',
        ),
    ]
