# Generated by Django 2.1.1 on 2020-04-28 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCharge',
            fields=[
                ('codeAcademicCharge', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourlyintensity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('codeArea', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameArea', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('codeCourse', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameCourse', models.CharField(max_length=100)),
                ('areaCourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.Area')),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('codeTimeTable', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayTimeTable', models.CharField(max_length=100)),
                ('startHourTimeTable', models.CharField(max_length=100)),
                ('endHourTimeTable', models.CharField(max_length=100)),
                ('courseTimeTable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='courses.AcademicCharge')),
            ],
        ),
        migrations.AddField(
            model_name='academiccharge',
            name='courseDictate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course'),
        ),
    ]
