# Generated by Django 2.1.1 on 2020-04-26 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('schoolyear', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nameGroup', models.CharField(max_length=100)),
                ('workingDay', models.PositiveSmallIntegerField(choices=[(1, 'Morning'), (2, 'Afternoon'), (3, 'Nigth')])),
                ('headquarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='institutions.Headquarters')),
            ],
        ),
    ]
