# Generated by Django 2.1.1 on 2020-05-25 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('codeCommunity', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameCommunity', models.CharField(max_length=255)),
                ('dateCommunity', models.DateField(auto_now_add=True)),
                ('descriptionCommunity', models.CharField(max_length=5000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Communitys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['codeCommunity', 'dateCommunity'],
            },
        ),
    ]
