# Generated by Django 2.1.1 on 2020-05-25 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='nameCommunity',
            new_name='titleCommunity',
        ),
        migrations.AlterField(
            model_name='community',
            name='descriptionCommunity',
            field=models.CharField(max_length=10000),
        ),
    ]
