# Generated by Django 2.1.1 on 2020-07-30 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0002_auto_20200525_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addfile',
            fields=[
                ('codefile', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='Community/')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='community.Community')),
            ],
        ),
        migrations.CreateModel(
            name='Replay',
            fields=[
                ('codereplay', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=5000)),
                ('datereplay', models.DateTimeField(auto_now_add=True)),
                ('replay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replays', to='community.Community')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
